asaskevich/govalidator

validator_test.go
sorry for making so much issus and pull requests ^^. But I really like this project :3
=> Add more test cases

validator.go, validator_test.go
according to http://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath
=> Add Check to IsFilePath to check wether the windows path isn't too lang

patterns.go, validator_test.go
I saw this on Reddit and thought it looked like an interesting library. I spotted the `TODO` for mixed case email validation and thoughtI'd have a go.
It seems adjusting the pattern was all it took. I've added a few extra tests to make sure and all looks well.
Over to you.
=> Support for miixed case emails

types.go
This might help you out with issue #30 . I am not entirely sure what the difference between url and requrl is. There seems to be some subtle differences. Like the person in issue #30 I couldn't validate a url with a subdomain. So I added these struct tags.
=> added requrl and requri to struct tags

error.go, validator.go, validator_test.go
@asaskevich awesome works. Thanks. :)
=> ValidateStruct: Go through all fields instead return immediately on first error

README.md, utils.go, utils_test.go
Added a truncate function that can shorten sentances without breaking
any words.
=> Truncate function

README.md, types.go, validator.go, validator_test.go
I need a struct tag to check string's length in certain range. I'm new to Golang, don't this is a good way to approach this feature.
=> Struct validator with parameters

README.md, types.go, validator.go, validator_test.go
I need to check Japanese string's length in a range, So I tried it.
Is this good? Or are there any ideas?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/77)
=> Add stringlength

validator_test.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/83)
=> Test for issue #72

README.md, types.go, validator.go, validator_test.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/101)
=> add matches validator for struct fields

README.md, patterns.go, types.go, validator.go, validator_test.go
add validation for semantic version strings
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/105)
=> add semver validation

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/120)
=> 	Updating .travis.yml to run the test suite with newer versions of go

error.go, validator.go
Added new feature - configuring custom error message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/121)
=> Added new feature - configuring custom error message

validator.go, validator_test.go
Fixes #133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/134)
=> Fix ErrorsByField when using custom validators

validator.go, validator_test.go
fixes #145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/152)
=> Add IsCIDR check

validator.go, validator_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/165)
=> Allow optional custom validations

patterns.go, types.go, validator.go, validator_test.go
Adds IsRFC3339 function for checking if string is matching [RFC 3339 spec](https://www.ietf.org/rfc/rfc3339.txt).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/176)
=> Support for RFC 3339 validation

validator_test.go
fix failed test about #158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/192)
=> fix failed test

patterns.go, validator_test.go
Not much more to say then what's in the subject line, add "_" to isURL() see issue #194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/199)
=> Issue #194: Add underscore to isURL()

README.md, types.go, validator.go
Untested ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/190)
=> [TASK] Add range

converter.go, numerics.go, utils.go, validator.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/206)
=> utils.go  – reducing number of casts; small refactoring

validator.go
Actually fixing this issue. https://github.com/asaskevich/govalidator/issues/218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/232)
=> Allow spaces between tags.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/244)
=> Added custom error messages docs to README

validator.go, validator_test.go
This PR fixes #327, #291, #251, #219.
=> Do not validate fields of struct type twice (validate each struct only once)

types.go, validator.go
1. Create Max String Length Validator
2. Create Min String Length Validator
3. Fix func name typo (isInRaw rename to IsInRaw)
I created a Min and Max String Length Validator because sometimes I just want to limit the minimum length of the variable with the unlimited maximum length and vice versa
=> New string length validator

validator.go
=> fix: Fix typo

validator.go
=> Refactoring

README.md, validator.go
* Fix #360 in README.
* Add a section on accessing individual errors in README.
* Added additional comment in func ValidateMap().
=> README.md ValidateMap, Error() changes and func ValidateMap comment change

README.md
fixes https://github.com/asaskevich/govalidator/issues/379
=> fix map validation example in README.md

patterns.go, types.go, validator.go, validator_test.go
I added IsIMEI validation function that is mentioned in CONTRIBUTING file. It has been tested.
=> Add IsIMEI validation function

README.md, validator.go, validator_test.go
Add IsRegex validator function which is based on RE2syntax (the syntax that go lang uses)
| Documentation | yes
| Bugfix         | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no
=> Add IsRegex Function (Issue #155)

validator.go, validator_test.go
add sha3-224, sha3-256, sha3-384 and sha3-512 hash validate
=> add sha3 hash validate

validator.go
BugFix: fix the bug relevant to isuue #416 
closes #416
| Documentation | yes/no
| Bugfix         | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no
=> fix credit card regex replacement

validator.go
| Documentation | no
| Bugfix         | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no
Simply & optimize (do less `ToInt` conversions ) code
=> Refactoring `IsCreditCard`: simplify and optimize code

README.md, types.go, validator.go, validator_test.go
| Documentation | yes
| Bugfix         | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no
I want to verify if a string is in the format of yyyymmdd.
https://github.com/asaskevich/govalidator/issues/499
=> feat IsYYYYMMDD function
