asaskevich/govalidator

validator.go, validator_test.go
I tested this against the new tests and it seems to work. +1 and -1 work for both UTFDigit and UTFNumeric.
=> Should fix the +- UTF bugs. 

validator.go, validator_test.go
example:
```go
type Example struct {
NotInt string `valid:"!int"`
}
```
=> Add possibility to negate a validator for a struct

validator.go
=> skip all struct fields tagged with `valid:"-"`

validator.go, validator_test.go
validate.
About the Problem:
Currently the validator simply skips each field which isn't of kind String. This way, one can't be sure whether or not the validator was successful or the kinds one tried to validate where simply not supported. 
Failing on not supported kinds is (IMO) better then a (possible) false sense of security
=> Validation fails now, if validator doesn't support the kind it should

validator.go
Problem:
Currently mistypes may lead to successful validation even though right typed a struct wouldn't be valid. 
example:
```go
type FooMistyped struct {
num string `valid:"requiered"`
}
type Foo struct {
num string `valid:"required"`
}
```
While ```FooMistyped{}``` would validate to "true" (as no validator with tag *requiered* exists), ```Foo{}``` wouldn't!
=> Validation fails on unknown validator

validator.go, validator_test.go
currently, required tag only effect on bool, int, string, etc... but not slice, map, struct
this PR fix required tag for all types
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/74)
=> fix required tag for all types

validator.go, validator_test.go
`StructValidate` fails to parse structs that contain pointers to non-structs like strings or booleans. The `typeCheck` will call `StructValidate` for all `reflect.Ptr` and `reflect.Interface` values. If A non-struct pointer is passed to `StructValidate` it will return an error (*function only accepts structs; got reflect.Value*) I added a test case for this behaviour and a fix in `typeCheck`. The element from a `reflect.Ptr` value is now passed to `typeCheck` where it is eventually send to `StructValidate` if it is a `reflect.Struct`. Optionally you could do the check without a recursive call to boost performance but that's up to you.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/75)
=> Make typeCheck compatible with pointer to non-struct

validator.go, validator_test.go
This pull request adds the ability to globally enforce validation rules to be defined for every public struct field. That way, you cannot forget to define a validation rule on a public struct field, even if you mark it as optional (via `valid:"optional,email"`) or as ignored (via `valid:"-"`).
Right now, it's a library-global switch that's activated by calling `govalidator.SetFieldsRequiredByDefault(true)` in an `init()` or even the `main()` function.
I added unit tests and they are all passing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/79)
=> Feature: fail struct validation for undefined validation rules

validator.go, validator_test.go
The `ErrorsByField(errorsOfStructValidation error)` function returns all errors as a `map[string]string` (key: field name, value: field error message).
Sadly, the only thing that's currently not possible (at least given this implementation) is the nested error hash someone asked for in asaskevich/govalidator#63. I'll try to take a crack at that in the next few days.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/81)
=> Add ErrorsByField function

validator.go, validator_test.go
Fixed making a custom array required crashes due to the fact that an array cannot be checked against `IsNil()`.
The error thrown by the test suite is:
```
panic: reflect: call of reflect.Value.IsNil on array Value [recovered]
panic: reflect: call of reflect.Value.IsNil on array Value
```
This fixes the crash and adds two more test cases for empty maps and slices as well (they behave correctly).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/82)
=> Fixed crash for required arrays that are empty

types.go, validator.go, validator_test.go
This adds basic custom type validations as shown in the tests. I didn't want to leave it in my fork although I'm not 100% happy with it. Additional tag options like `required` or `optional` don't work for custom type validations. As it's implemented right now I can't let additional proceed due to the fact that this would trigger the base type validations as well (i.e. in the unit test I added: `type CustomByteArray [6]byte` which would be validated as an array of `unit8`s as well – that's undesired here).
So, my question is: is this a good first step or would I need to go back to the drawing board? Alas, it doesn't break anything or BC in any way – test suite is still green.
Whatever you decide, you might want to take a look at the panic fix I added in 297a3e5 – you might like to …
=> Add basic custom type validations

validator.go, validator_test.go
This fix passes all existing tests cases and the added test for `"google" false`.
The main issue we have to fight against for this is that `url.Parse` only populates `Path` for values like `google` and `foobar.com`. This is the way `url.Parse` is coded and so working with that I've put in some extra checks after the call to `url.Parse` to check some basics on each part of the `url.URL` struct.
It should be clear now and I think we have covered it all.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/84)
=> Correct IsURL

validator.go
Right now if ValidateStruct got invalid argument (not a Struct) in always print:
```
function only accepts structs; got reflect.Value
```
Because type of `val` is always `reflect.Value` (https://github.com/asaskevich/govalidator/blob/330d28f27e5daa21b9656342a919a2262b830027/validator.go#L511).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/96)
=> fix error log when ValidateStruct get invalid arg

error.go, validator.go, validator_test.go
When ErrorsByField try to parse errors containing semi-colons we get a
panic error : index out of range, so instead of trying to parse string from error we use
plain error
srv_1   | Title: lkdqskjdk does not validate as length(10|300);AdminEmail: qsjd;jdhq does not validate as email;ParticipantEmails: [qlsjdlqk] does not validate as participantEmails;
srv_1   | 2015/11/07 21:59:16 Panic recovery -> runtime error: index out of range
srv_1   | /usr/local/go/src/runtime/panic.go:423 (0x429219)
srv_1   |       gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
srv_1   | /usr/local/go/src/runtime/panic.go:12 (0x4276f9)
srv_1   |       panicindex: panic(indexError)
srv_1   | /go/src/github.com/asaskevich/govalidator/validator.go:840 (0x6858e1)
srv_1   | …
=> Fixed panic : ErrorsByField crash app

validator.go
Hello,
Addresses like ::ffff:c0a8:101 are marked as invalid IPv6 addresses and valid IPv4 addresses :
http://play.golang.org/p/4tNuUR7_yq
This is related to the way addresses are handled in the net/ip package ([16]byte array for both types).
Seems the easiest way to deal with this, is to check if the string is an IP address and, depending on the type, if it contains a dot or a column.
Ref: This [discussion] (http://stackoverflow.com/questions/22751035/golang-distinguish-ipv4-ipv6) on stackoverflow, this [issue] (https://github.com/golang/go/issues/8985) and the [code of ParseIP] (https://golang.org/src/net/ip.go#L638)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/100)
=> Fix validation of IPv4-mapped IPv6 addresses

validator.go
When ErrorsByField was called with a error of type Errors the items of Errors wasn't verified.
I changed to verify the item's type. In case of being Error, the new error is added to the map and when is Erros the method ErrorsByField  is called recursively.
With only these change will be possible to override some errors with the same name and also the error message starts to being is a little confuse.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/113)
=> Fix for issue panic with ErrorsByField #112

README.md, arrays.go, arrays_test.go, converter_test.go, error.go, error_test.go, numerics_test.go, types.go, utils.go, utils_test.go, validator.go, validator_test.go
- fixed various code smells and coding style that the static analyzers found (vet, vetshadow, golint)
- updated test suite errors reported in #118
I enhanced the custom type validators so their validation functions get the object being validated passed as a second argument. It is a BC break but the changes necessary are mechanical in nature (see the updated unit test for an example on how this can be used).
This is not finished yet (working on fixing #116) but I wanted to put this out there in order to ask you about the BC break: is that even an option? I thought about doing it in a backwards-compatible way but that would involve reflection. Variadic parameters aren't an option either. The only other way would be to wrap the value to validate and the object being validated in a custom …
=> [BC break] Custom validation with context + smaller fixes

types.go, validator.go, validator_test.go
The validation tag options were parsed into a string slice and were constantly being searched with string operations (multiple splits, regexes, etc.) – I made it a map to make lookups for validators and their custom error message easier and the code shorter.
No BC breaks, no unit test fixes and no regressions.
I added an example of nested validation for #129.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/132)
=> Validator tag options map

validator.go
Create constants for minimum and maximum character count in URLs
use utf8.RuneCountInString to check for strings that are too long or
short
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/167)
=> Fixes for #33

validator.go
Hi,
This is a change to allow optional tags for custom type validators, there is an existing test that pass now thanks to my modification so I think it used to work in the past. What do you think ?
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/185)
=> Move optional/required check before custom validators validation

types.go, validator.go, validator_test.go
This is based on the ISO4217 list of currencies.
See:
- https://www.iso.org/iso-4217-currency-codes.html
- https://www.currency-iso.org/en/home/tables/table-a1.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/196)
=> Add ISO4217 support for currency validation

validator.go, validator_test.go
Current JSON tag handling will leak tag options into the error message. For
instance with this type:
```
type Foo struct {
Foo string `json:"foo,omitempty" valid:"-,required"`
}
```
The error message will contain: 'foo,omitempty: non zero value required;', while
one would expect only 'foo: non zero..'
@asaskevich 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/195)
=> validator: proper handling of JSON tag options

validator.go
Feel free to merge if you want, usage example:
```
type User struct {
EmailField     `bson:",inline"`
LastLoginDate  time.Time     `json:"lastLoginDate" bson:"lastLoginDate"`
OrganizationId bson.ObjectId `json:"organizationId" bson:"organizationId" valid:"required"`
ProfileFields  `bson:",inline"`
}
type UserWithPassword struct {
User          `bson:",inline"`
PasswordField `bson:",inline"`
}
type ProfileFields struct {
FirstName string `json:"firstName" bson:"firstName"`
LastName  string `json:"lastName" bson:"lastName"`
Phone     string `json:"phone"`
AvatarUrl string `json:"avatarUrl" bson:"avatarUrl"`
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/201)
=> fixed validator to be able to validate inline structs

validator.go
When validating structs with nested structs like this:
```go
type Comment struct {
Text   string `valid:"required"`
Author User   `valid:"-"`
}
```
I do not want to validate `User` for each `Comment` so having an option to explicitly ignore it is nice. I think this would be expected behavior in such a case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/217)
=> Do not validate nested structs when explicitly ignored

error.go, error_test.go
Makes it easier to split the string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/227)
=> Use strings.Join to join error strings

error.go, validator.go, validator_test.go
In some cases it is convenient to have access to the validator that failed
the validation in the error response.  This fix exposes the validator that was
used in the error so it can be used downstream.
My case has it returned in a JSON response so that errors can be shown in a
user interface more conveniently.  Given a struct defined as follows:
```go
type Page struct {
Address string `db:"address" json:"address" default:"" valid:"url"`
}
```
... that uses the built-in url validation, I'd like to be able to create a response as follows:
```json
{
"error": {
"code": "validation",
"message": "Field validation failed",
"details": {
"address": {
"code": "url",
"key": "pageAddress",
"message": "name: non-url does not validate as url"
}
}
}
}
```
This commit allows the `"code": "url"` part to …
=> Expose the Validator that Failed in the Error

validator.go, validator_test.go
The validator code will correctly use JSON field names if those are defined for
given type. However, it is possible to set JSON tags with "-" ignore setting in
order to prevent the field from being (de-)serialized to/from JSON. In this
case, the validation error message contain '-' as field name (as it was defined
in JSON tag) instead of the struct field name.
Take this type as an example:
```
type Foo struct {
Foo string `json:"-" valid:"-,required"`
}
```
The error message will contain: `-: non zero value required`, while one would
expect `Foo: non zero..`
@asaskevich minor fix for JSON tag names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/233)
=> validator: proper handling of JSON fields with ignore tag

utils.go, utils_test.go
When running CamelCaseToUnderscore(str), if the string contained an
underscore character, that underscore character would appear twice in
the final string. For Example: my_func => my__func
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/235)
=> Don't append underscore characters when converting a string to camelCase

validator.go
We currently have a weird behaviour if we have basic and custom validators on a field with a JSON tag. 
If a custom validator fails the name inside the `govalidator.Error` will be the name of the field won't be the JSON tag one but if it's a default validator it will be the JSON tag one.
Eg: 
```
func init() {
valid.CustomTypeTagMap.Set("dummy-validator", valid.CustomTypeValidator(func(i interface{}, o interface{}) bool {
switch v := i.(type) {
case float64:
return v > 10
default:
return false
}
}))
}
type DummyPayload struct {
DummyValue  float64 `json:"dummy_value" valid:"required,dummy-validator,url"`
}
```
```
v := DummyPayload{DummyValue: 5}
ok ,err := valid.ValidateStruct(v)
```
The `govalidator.Error.Name` inside the `govalidator.Errors` will be `DummyValue` 
```
v := …
```
=> Add json name to Errors 

numerics.go, numerics_test.go
**InRange** is backward compatible and now will handle int, float32 or float64 if any of the parameters are not of the same type boolean value **false** is returned.  InRange is just a simple wrapper to the 3 specific range checks:  **InRangeInt**, **InRangeFloat32**, **InRange64**.
Yes, in each of the specific implementations the code seems to be redundant but I believe this is unavoidable due to _Go_ being strictly typed.  We could convert them inside **InRange** and only have the one function (we would still have 3 sets of comparing logic due to strict type) but why not have the other functions for convenience.
Modified InRangeTest test all 3 support types and simple test where a mix of types are given (returns false).  As included unit tests for each the specific range checks.
--- …
=> Issue #233 - Added InRangeInt, InRangeFloat32, InRange64 & modified InRange

validator.go, validator_test.go
Fixed, now allows colon for port when Url Scheme doesn't exist.
The solution detects if there is a colon and no url scheme exits (searches for **://**) it then fakes out _url.Parse()_ by appending **http://** , originally I was thinking for specifically looking for either https or http based on the comment in the golang url.parse function the URL,"... _is assumed to have arrived via an HTTP request_", but because govalidator supports other schemes like ftp (see patterns.go).  The faked out url with the appended value is only used in urlParse.  The original given url is still used in the _rxURL.MatchString(str)_.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/240)
=> Fixe for _ in URL makes them invalid #212

patterns.go, validator.go, validator_test.go
There is already **IsLowerCase** and **IsUpperCase**, which makes consistent with what other string libraries do.  
**HasLowerCase** checks if there is at least one character that is lower case, if so returns true.  In keeping with consistency with IsLowerCase when the string is NULL, true is returned.
**HasUpperCase** checks if there is at least one character that is upper case, if so returns true.  In keeping with consistency with IsUpperCase when the string is NULL, true is returned.
Instead of appending the new validators at the end of the _validators.go_ file I put them near IsLowerCase and IsUpperCase, thinking it makes more sense from a grouping perspective.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Issue 236 - Add validators for HasLowerCase and HasUpperCase with unit tests

validator_test.go
My apologies, I checked in the unit test last time with the test intentionally busted to eyeball the output.  Fixed now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/243)
=> Fix test for TestFieldRequiredByDefault & TestMultipleFieldsRequiredByDefault

validator.go, validator_test.go
This fixes https://github.com/asaskevich/govalidator/issues/210
The diff is quite big because gofmt went through the test file.
Strange thing that test had substructs as pointers, but in fact, the validation of these structs didn't work.
I've added another example to the test to verify exactly this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/249)
=>  Validate the child struct if it's a pointer

validator_test.go
Go's parser gives the error below. I think it is not expected to parse IRC URLs
like this one:
parse irc://#channel@network: net/url: invalid userinfo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/264)
=> Remove broken IRC URL parsing test.

validator_test.go
The previously-used URL format is not valid as per either of these two:
https://www.w3.org/Addressing/draft-mirashi-url-irc-01.txt
https://www-archive.mozilla.org/projects/rt-messaging/chatzilla/irc-urls.html
Further, Go’s net/url package no longer parses the syntax as of
https://github.com/golang/go/commit/ba1018b4549f3edc257221cc8e49221255e03290
fixes #250
related to https://github.com/golang/go/issues/23657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/257)
=> validator_test: remove invalid irc:// URLs

validator.go, validator_test.go
That's a quick fix to support basic stuff like **range()** **in()** validation tags on integer and float types in structs.
It's not much efficient because govalidator is doing int -> str -> int double conversion behind the scenes, but I guess that can be improved in future without breaking the API.
Test included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/asaskevich/govalidator/263)
=> Add support for ParamValidator functions to process integers

validator.go, validator_test.go
uses newer functions not available in old go versions
but I guess support should be rechecked.
=> some simplifications

patterns.go, validator.go, validator_test.go
Refer to issue #247 
Although, I suggested **IsBlank** that that can get confusing with **IsNull** and in other languages _isEmpty_, it is debatably not completely clear.
In my opinion,
**HasWhitespace** is more explicit, does it have any whitespace
and
**HasWhitespaceOnly** is more explicit as well, does it only have whitespace
Included unit tests as well.
=> Add hasWhitespace and hasWhitespaceOnly

validator.go
This PR validates the inner struct when its passed onto a field that is defined as an interface. The current implementation only checks for child structs that are pointers.
=> Validate the child struct when its an interface

README.md, types.go, validator.go, validator_test.go
Reverts asaskevich/govalidator#286
=> Revert "(Enhancement) Validator: Adding more concrete base64 validation, Enabling []int validation "

README.md
1. Complete Validators with parameters Section
```
"stringlength(min|max)": StringLength,
"rsapub(keylength)" : IsRsaPub,
```
2. Add Example to create custom tags with parameter in example section
```
// Add your own struct validation tags with parameter
govalidator.ParamTagMap["animal"] = govalidator.ParamValidator(func(str string, params ...string) bool {
species := params[0]
return str == species
})
govalidator.ParamTagRegexMap["animal"] = regexp.MustCompile("^animal\\((\\w+)\\)$")
```
=> Complete the read.me

utils.go
This PR fixes a few typos in utils.go methods docs I've come across while browsing the code.
=> Fix typos in utils.go

validator_test.go
Improving the IsCreditCard validation tests by adding more card brands, which reveals some card brands won't pass our validation logic.
```
// below should be valid, do they respect international standards?
// is our validator logic not correct?
{"diners club international", "30190239451016", false,},
{"rupay", "6521674451993089", false,},
{"mir", "2204151414444676", false,},
{"china unionPay", "624356436327468104", false,},
```
Sorry about all the whitespace changes, it appears the file wasn't gofmt'ed. My changes start at L:1392: https://github.com/asaskevich/govalidator/compare/master...lfaoro:test-iscreditcard?expand=1#diff-bf215ece4e5166da723b1e19a0d6b1cdR1392
The cards are generates from: https://ccard-generator.com/bulk-generate/visa
=> Test iscreditcard

validator.go, validator_test.go
Currently `govalidator` skips validation of zero numbers, empty strings, and other zero values of any type. It treats them as always valid. On the other hand, `govalidator` errs when a 'required' field has a zero value which disallows entering zero values into required fields.
The goal of this PR is to solve both problems: to validate zero values and to allow 'required' fields to have zero/empty values.
The main idea is to skip validation only when we are sure that a value is a nil-value (we can distinguish nil values from zero/empty values only for pointers, interfaces, maps, and slices; we consider all other values as non-nil values). All non-nil values are being validated. The 'required` validator errs only for nil values.
If one wants to check that some required string or number is …
=> Validate empty values

validator_test.go
The test uses `bar.coffee` domain which doesn't exist and cannot be resolved. Let's replace it with `driftaway.coffee`.
=> Fix TestIsExistingEmail()

CONTRIBUTING.md, README.md, types.go, validator.go, validator_test.go
Adds `ValidateMap` which can be used to validate `map[string]interface{}` against a validation map in the form `map[string]interface{}`. The validation map values can be either a string in the same form as the tags used in structs (without the key `valid`) or a `map[string]interface{}` for recursive validation. The map to be validated can contain values of any kind.
Example usage added in the README (copied from #224)
```go
var mapTemplate = map[string]interface{}{
"name":"required,alpha",
"family":"required,alpha",
"email":"required,email",
"cell-phone":"numeric",
"address":map[string]interface{}{
"line1":"required,alphanum",
"line2":"alphanum",
"postal-code":"numeric",
},
}
var inputMap = map[string]interface{}{
"name":"Bob",
"family":"Smith",
"email":"foo@bar.baz", …
```
=> implement ValidateMap

.circleci/config.yml
`go fmt` doesn't change it's exit code when it finds formatting violations, so we need to diff it's output with "nothing".
=> Add go fmt as a CI step

README.md, validator_test.go
A `func(interface{}, interface{}) bool` can be used in all places where a `CustomTypeValidator` is needed without the need for a type conversion.
=> Remove unneeded type conversion for CustomTypeValidator

error.go, error_test.go, validator_test.go
Fixes https://github.com/asaskevich/govalidator/issues/380
Test cases were broken for two reasons:
1. Multiple errors gets appended into an Errors struct without any guarantee on the order, so string comparison with the expected value sometimes fails when the order doesn't match.
2. foo@bar.museum returns false instead of the expected true.
This PR fixes both, by sorting the errors array when stringifying, and removing the broken email test case.
=> Fix test cases

validator_test.go
I went through the Issue list and wanted to see if I could contribute in a small way. Noticed Issue https://github.com/asaskevich/govalidator/issues/334 and decided to take a look.
Added a test case to the validator_test.go to cover the reported failure. Unable to reproduce given the same required value and input. At this point it may be assumed this behavior has been addressed in more recent updates. 
Adding test case to cover the behavior for the future.
=> Add test to verify behavior of required check on byte slice.

README.md
ParamTagMap already has `minstringlength` and `maxstringlength` but they are not included in the readme.
Seeing how all other possible tags with params are included, these should probably be included too.
=> Include the min and max string length checks

patterns.go, validator.go, validator_test.go
since the IsFilePath() function just checked the absolute paths #278, I've added IsUnixFilePath() & IsWinFilePath() functions for checking both absolutes and relative file paths in Unix and Windows.  
Example:
`isUnixFilePath("relative_file_path") => true`
`isUnixFilePath("./relative_file_path") => true`
`isUnixFilePath("../relative_file_path") => true`
`isWinFilePath("relative_file_path") => true`
`isWinFilePath("..\relative_file_path") => true`
`isWinFilePath("..\\relative_file_path") => false`
IsUnixFilePath() & IsWinFilePath() functions are using UnixARPath & WinARPath regex in patterns.go
there are TestIsWinFilePath() & TestIsWinFilePath() test functions in validator_test.go for to demonstrate more
=> Feature: absolute and relative file path validator functions for Unix & Windows #278

README.md, go.mod
| Documentation | yes
| Bugfix         | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes
This change includes the major version in the module path.
This will ensure appropriate semver tagging.
Closes #384.
=> fix: include major in go.mod module directive

go.mod
| BC Break      | yes
`go get gopkg.in/asaskevich/govalidator v11.0.1`  and `go get gopkg.in/asaskevich/govalidator.v11` should work 
```
go get gopkg.in/asaskevich/govalidator.v11                                                                                  
go: gopkg.in/asaskevich/govalidator.v11@v11.0.1: invalid version: go.mod has non-....v11 module path "github.com/asaskevich/govalidator" at revision v11.0.1
go get gopkg.in/asaskevich/govalidator v11.0.1                                                                                 
go: gopkg.in/asaskevich/govalidator: unrecognized import path "gopkg.in": parse https://gopkg.in/?go-get=1: no go-import meta tags ()
go: unrecognized import path "v11.0.1": https fetch: Get …
```
=> chore: version go module path
